/**
 * This file was generated by @pikku/cli@0.11.1
 */
/**
 * This provides the structure needed for TypeScript to be aware of workflows and their input/output types
 */



// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type QueueWorkerInput = { message: string; fail: boolean; }
export type QueueWorkerOutput = { result: string; }
export type QueueWorkerWithMiddlewareInput = { message: string; }
export type QueueWorkerWithMiddlewareOutput = { result: string; }

interface WorkflowHandler<I, O> {
    input: I;
    output: O;
}

export type WorkflowMap = {
};


/**
 * Type-safe workflow client API
 */
export type WorkflowClient<Name extends keyof WorkflowMap> = {
  /**
   * Start a new workflow run
   */
  start: (input: WorkflowMap[Name]['input']) => Promise<{ runId: string }>;

  /**
   * Get a workflow run by ID
   */
  getRun: <output extends keyof WorkflowMap[Name]>(runId: string) => Promise<WorkflowMap[Name][output]>;

  /**
   * Cancel a running workflow
   */
  cancelRun: (runId: string) => Promise<boolean>;
}

/**
 * Map of all registered workflows with type-safe client APIs
 */
export type TypedWorkflowClients = {
  [Name in keyof WorkflowMap]: WorkflowClient<Name>;
}
  