/**
 * This file was generated by @pikku/cli@0.11.3
 */
/**
 * This provides the structure needed for TypeScript to be aware of channels
 */



export type ProcessReminderInput = unknown
export type ProcessReminderOutput = unknown
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type PikkuFn_src_wirings_rpc_wiring_ts_L32C9Input = { rpcName: string; }

interface ChannelHandler<I, O> {
    input: I;
    output: O;
}

export type ChannelsMap = {
};

export type ChannelDefaultHandlerOf<Channel extends keyof ChannelsMap> =
    ChannelsMap[Channel]['defaultMessage'] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;

export type ChannelWiringHandlerOf<
    Channel extends keyof ChannelsMap, 
    Route extends keyof ChannelsMap[Channel]['routes'], 
    Method extends keyof ChannelsMap[Channel]['routes'][Route],
> =
    ChannelsMap[Channel]['routes'][Route][Method] extends { input: infer I; output: infer O }
        ? ChannelHandler<I, O>
        : never;
