/**
 * This file was generated by the @pikku/cli
 */
import './queue/pikku-queue-workers-wirings-meta.gen.js'
import './rpc/pikku-rpc-wirings-meta.gen.js'
import './function/pikku-functions-meta.gen.js'
import './function/pikku-functions.gen.js'
import './schemas/register.gen.js'
import './queue/pikku-queue-workers-wirings.gen.js'