/**
 * This file was generated by @pikku/cli@0.11.2
 */
import { pikkuState } from '@pikku/core'
pikkuState('http', 'meta', {
  "get": {},
  "post": {},
  "put": {},
  "delete": {},
  "head": {},
  "patch": {},
  "options": {}
})