/**
 * This file was generated by @pikku/cli@0.11.2
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */
    


// Custom types are those that are defined directly within generics
// or are broken into simpler types
export type QueueWorkerInput = { message: string; fail: boolean; }
export type QueueWorkerOutput = { result: string; }
export type QueueWorkerWithMiddlewareInput = { message: string; }
export type QueueWorkerWithMiddlewareOutput = { result: string; }

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript


interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  