/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('queue', 'meta', {
  "hello-world-queue": {
    "pikkuFuncName": "queueWorker",
    "queueName": "hello-world-queue"
  }
})