/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('queue', 'meta', {
  "hello-world-queue": {
    "pikkuFuncName": "pikkuFn_src_queue_worker_functions_ts_L6C3",
    "queueName": "hello-world-queue"
  }
})