/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "queueWorker": {
    "pikkuFuncName": "queueWorker",
    "inputSchemaName": "QueueWorkerInput",
    "outputSchemaName": "QueueWorkerOutput"
  },
  "queueWorkerWithMiddleware": {
    "pikkuFuncName": "queueWorkerWithMiddleware",
    "inputSchemaName": "QueueWorkerWithMiddlewareInput",
    "outputSchemaName": "QueueWorkerWithMiddlewareOutput"
  }
})