/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "queueWorker": {
    "pikkuFuncName": "queueWorker",
    "name": "queueWorker",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": "QueueWorkerInput",
    "outputSchemaName": "QueueWorkerOutput",
    "inputs": [
      "QueueWorkerInput"
    ],
    "outputs": [
      "QueueWorkerOutput"
    ],
    "isDirectFunction": true
  },
  "queueWorkerWithMiddleware": {
    "pikkuFuncName": "queueWorkerWithMiddleware",
    "name": "queueWorkerWithMiddleware",
    "services": {
      "optimized": true,
      "services": [
        "logger"
      ]
    },
    "inputSchemaName": "QueueWorkerWithMiddlewareInput",
    "outputSchemaName": "QueueWorkerWithMiddlewareOutput",
    "inputs": [
      "QueueWorkerWithMiddlewareInput"
    ],
    "outputs": [
      "QueueWorkerWithMiddlewareOutput"
    ],
    "isDirectFunction": false,
    "middleware": [
      {
        "type": "wire",
        "name": "loggingMiddleware",
        "inline": false
      }
    ]
  }
})