/**
 * This file was generated by the @pikku/cli
 */
/* Import and register RPCs */
import { addFunction } from '@pikku/core'
import { queueWorker } from '../../src/queue-worker.functions.js'

addFunction('queueWorker', { func: queueWorker })