/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "queueWorker": {
    "pikkuFuncName": "queueWorker",
    "inputSchemaName": "QueueWorkerInput",
    "outputSchemaName": "QueueWorkerOutput"
  },
  "queueWorkerWithMiddleware": {
    "pikkuFuncName": "queueWorkerWithMiddleware",
    "inputSchemaName": "QueueWorkerWithMiddlewareInput",
    "outputSchemaName": "QueueWorkerWithMiddlewareOutput"
  }
})