/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "pikkuFn_src_queue_worker_functions_ts_L6C3": {
    "pikkuFuncName": "pikkuFn_src_queue_worker_functions_ts_L6C3",
    "name": "queueWorker",
    "services": {
      "optimized": true,
      "services": []
    },
    "schemaName": "QueueWorkerInput",
    "inputs": [
      "QueueWorkerInput"
    ],
    "outputs": [
      "QueueWorkerOutput"
    ]
  }
})