/**
 * This file was generated by @pikku/cli@0.11.3
 */
import { addSchema } from '@pikku/core/schema'

import * as ProcessReminderInput from './schemas/ProcessReminderInput.schema.json' with { type: 'json' }
addSchema('ProcessReminderInput', ProcessReminderInput)


import * as ProcessReminderOutput from './schemas/ProcessReminderOutput.schema.json' with { type: 'json' }
addSchema('ProcessReminderOutput', ProcessReminderOutput)


import * as OnTestEventInput from './schemas/OnTestEventInput.schema.json' with { type: 'json' }
addSchema('OnTestEventInput', OnTestEventInput)


import * as OnTestEventOutput from './schemas/OnTestEventOutput.schema.json' with { type: 'json' }
addSchema('OnTestEventOutput', OnTestEventOutput)
