/**
 * This file was generated by the @pikku/cli
 */
import { addSchema } from '@pikku/core/schema'

import * as QueueWorkerInput from './schemas/QueueWorkerInput.schema.json' with { type: 'json' }
addSchema('QueueWorkerInput', QueueWorkerInput)


import * as QueueWorkerOutput from './schemas/QueueWorkerOutput.schema.json' with { type: 'json' }
addSchema('QueueWorkerOutput', QueueWorkerOutput)


import * as QueueWorkerWithMiddlewareInput from './schemas/QueueWorkerWithMiddlewareInput.schema.json' with { type: 'json' }
addSchema('QueueWorkerWithMiddlewareInput', QueueWorkerWithMiddlewareInput)


import * as QueueWorkerWithMiddlewareOutput from './schemas/QueueWorkerWithMiddlewareOutput.schema.json' with { type: 'json' }
addSchema('QueueWorkerWithMiddlewareOutput', QueueWorkerWithMiddlewareOutput)
